# runtime: MultiThread
runtime: CurrentThread
dns_resolver: Hickory
# dns_resolver: Tokio
hosts:
  - addr: 127.0.0.1:2776
    kind: Tls
    certs:
      certs: "certs/cert.pem"
      key: "certs/key.pem"
      watch:
        kind: Debounce
        duration: 2s
    upstreams:
      - domain: 127.0.0.1
        port: 8001
        kind: Tcp
      - domain: 127.0.0.1
        port: 8081
        kind: Tcp

  - addr: 127.0.0.1:2777
    kind: Tcp
    upstreams:
      - domain: 127.0.0.1
        port: 8001
        kind: Tcp
      - domain: 127.0.0.1
        port: 8081
        kind: Tcp
        
  - addr: 127.0.0.1:2778
    kind: Tcp
    upstreams:
      - domain: www.google.com
        port: 443
        kind: Tls
        certs: 
          kind: WebPki
  
  # Connect to this without tls and it will forward the stream to its self with tls then it will forward it to the upstreams defined in `127.0.0.1:2776`
  - addr: 127.0.0.1:2779
    kind: Tcp
    upstreams:
      - domain: localhost
        port: 2776
        kind: Tls
        certs: 
          kind: File
          file:
            certs: "certs/cert.pem"
            watch:
              kind: Debounce
              duration: 2s